[sf_usage_app]
account= "pr65711.ap-southeast-1"
user="snowgovernance"
password= "Sravani@23"
role="accountadmin"
warehouse= "COMPUTE_WH"
database="UTIL_DB"
schema="ADMIN_TOOLS"

[theme]
primaryColor = "#6D7294"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor= "#262730"


